version: '3.8'

services:
  webapp:
    image: kennethreitz/httpbin
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:80"]
      interval: 10s
      timeout: 5s
      retries: 5
    ports:
      - "8080:80"
