version: '3.8'

services:
  webapp:
    image: kennethreitz/httpbin
    # healthcheck:
    #   test: ["CMD", "curl", "-f", "http://0.0.0.0:80"]
    #   interval: 10s
    #   timeout: 5s
    #   retries: 5
    ports:
      - "80:80"
