apiVersion: v1
kind: Service
metadata:
  name: httpbin-diffy
  labels:
    app: httpbin-diffy
spec:
  ports:
  - name: http-proxy
    port: 8880
  - name: http-admin
    port: 8881
  - name: http-console
    port: 8888    
  selector:
    app: httpbin-diffy
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: httpbin-diffy
    version: v2
  name: httpbin-diffy-v2
spec:
  replicas: 1
  selector:
    matchLabels:
      app: httpbin-diffy
      version: v2
  template:
    metadata:
      labels:
        app: httpbin-diffy
        version: v2
    spec:
      containers:
      - image: diffy/diffy
        imagePullPolicy: Always
        livenessProbe:
          exec:
            command:
            - curl
            - localhost:8888
          initialDelaySeconds: 10
          periodSeconds: 60
          timeoutSeconds: 1
        name: httpbin-diffy
        env:
        - name: candidate
          value: "httpbin-candidate:8080"
        - name: master.primary
          value: "httpbin-master:8080"
        - name: master.secondary
          value: "httpbin-master:8080"
        - name: service.protocol
          value: "http"
        - name: proxy.port
          value: "8880"
        - name: rootUrl
          value: "localhost:8888"
        - name: serviceName
          value: "Example Service"
        - name: otel.javaagent.debug
          value: "false"
        - name: otel.metrics.exporter
          value: "none"
        - name: otel.traces.exporter
          value: "jaeger"
        - name: otel.exporter.jaeger.endpoint
          value:  "http://tempo:14250"
        - name: otel.exporter.jaeger.traces.endpoint
          value:  "http://tempo:14250"
        - name: otel.resource.attributes
          value: "service.name=diffy"
        - name: spring.application.name
          value: "diffy"
        - name: logging.level.web
          value: "INFO"
        - name: logging.level.io.opentelemetry
          value:  "WARN"
        - name: logging.level.root
          value: "INFO"
        - name: logging.file.name
          value: "/app/logs/diffy.log"
        - name: logging.file.max-size
          value: "10MB"
        - name: logging.file.max-history
          value: 1
        - name: logging.file.clean-history-on-start
          value: "true"
        - name: spring.mongodb.embedded.version
          value: "4.4.13"
        ports:
        - containerPort: 8888
          name: http-console
          protocol: TCP
        - containerPort: 8880
          name: http-proxy
          protocol: TCP
        - containerPort: 8881
          name: http-admin
          protocol: TCP
        readinessProbe:
          exec:
            command:
            - curl
            - localhost:8888
          initialDelaySeconds: 10
          periodSeconds: 60
          timeoutSeconds: 1
        securityContext:
          privileged: false
