# This is an example configuration, for production grade configuration see the Keycloak documentation.
# See https://www.keycloak.org/server/configuration
# See https://www.keycloak.org/server/all-config
command:
  - "/opt/keycloak/bin/kc.sh"
  - "--verbose"
  - "start"
  - "--http-enabled=true"
  - "--http-port=8080"
  - "--hostname-strict=false"
  - "--hostname-strict-https=false"
  - "--spi-events-listener-jboss-logging-success-level=info"
  - "--spi-events-listener-jboss-logging-error-level=warn"
  - "--features=declarative-user-profile"

extraEnv: |
  - name: KC_PROXY
    value: "passthrough"
  - name: KC_HOSTNAME_ADMIN_URL
    value: "https://humble-xylophone-g4jjqgpg7gcwxqx-3001.app.github.dev/auth"
  - name: KC_HOSTNAME_URL
    value: "https://humble-xylophone-g4jjqgpg7gcwxqx-3001.app.github.dev/auth"
  - name: PROXY_ADDRESS_FORWARDING
    value: "true"
  - name: KC_PROXY
    value: "edge"
  - name: KEYCLOAK_EXTRA_ARGS
    value: "-Dkeycloak.profile.feature.declarative_user_profile=enabled"
  - name: KEYCLOAK_ADMIN
    valueFrom:
      secretKeyRef:
        name: {{ include "keycloak.fullname" . }}-admin-creds
        key: user
  - name: KEYCLOAK_ADMIN_PASSWORD
    valueFrom:
      secretKeyRef:
        name: {{ include "keycloak.fullname" . }}-admin-creds
        key: password
  - name: JAVA_OPTS_APPEND
    value: >-
      -XX:+UseContainerSupport
      -XX:MaxRAMPercentage=50.0
      -Djava.awt.headless=true
      -Djgroups.dns.query={{ include "keycloak.fullname" . }}-headless

dbchecker:
  enabled: true

database:
  vendor: postgres
  hostname: keycloak-postgresql
  port: 5432
  username: keycloak
  password: keycloak
  database: keycloak

secrets:
  admin-creds:
    annotations:
      my-test-annotation: Test secret for {{ include "keycloak.fullname" . }}
    stringData:
      user: admin
      password: secret
