name: trivy-security-scanning
on: push

permissions:
  security-events: write # To upload sarif files

jobs:
  chart-test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3.1.0
      
      - name: Run Trivy vulnerability scanner in IaC mode
        uses: aquasecurity/trivy-action@master # tag=0.8.0
        with:
          scan-type: 'config'
          hide-progress: false
          format: 'sarif'
          scan-ref: 'deployment/mailhog'
          output: 'trivy-results.sarif'
          exit-code: '0'
          ignore-unfixed: true

      - name: Upload Trivy scan results to GitHub Security tab
        uses: github/codeql-action/upload-sarif@v3 # v2.1.34
        with:
          sarif_file: 'trivy-results.sarif'